server:
  port: 8889 # 可自行配置

spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #不加这句则默认为myisam引擎
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    #  接口接收时间参数 String->Date
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  #数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/xxx?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8  #&rewriteBatchedStatements=true
    username: root # 自行配置
    password: xxx # 自行配置

    #连接池
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
      auto-commit: true
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: localhost
    port: 6379

  data:
    redis:
      repositories:
        enabled: false

jwt:
  clientId: xxxxxxx # 自行配置
  secret: xxxxxxx # 自行配置
  name: api
  expiretime: 2592000000  #  //毫秒,1个月

#自定义配置